---
title: "Beyond bias: A registered examination of the validity of using line bisection
  to measure non-lateralised attention"
author: "Alexandra G. Mitchell, Aimal Ahmad Kahn, Helen Stocks & Robert D. McIntosh"
output:
  word_document: 
    reference_docx: word_template.docx

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Abstract**

Line bisection is a task widely used to assess lateral asymmetries of attention, in which participants are asked to mark the midpoint of a horizontal line. The Directional Bisection Error (DBE) from the objective midpoint of the line is the traditional measure of performance. However, an alternative method of studying bisection behaviour, the end-point weightings method, has been proposed. This method produces two measures of performance, end-point weightings bias (EWB) and end-point weightings sum (EWS). Whilst EWB measures attentional asymmetry, it has been suggested that EWS quantifies the total (non-lateralised) attention allocated to the task. If EWS provides a valid index of non-lateralised attention, then changes in tonic and phasic alertness should systematically affect EWS. Here, we present an experiment that aims to formally test this prediction, using time on task to manipulate tonic alertness, and unpredictable auditory tones, presented simultaneously with line stimuli, to manipulate phasic alertness. If EWS is a valid measure of non-lateralised attention, then it should reduce with increased time-on-task (tonic) and increase on trials accompanied by an alerting tone (phasic). We will also test the effect of arousal and motivation on lateralised attention, as measured by EWB.

**1. Introduction**

  1.1 An alternative approach to the line bisection task
The line bisection task is a simple and common method for assessing lateral asymmetries of spatial attention. In the standard task, a horizontal line is presented to a participant, who is asked to mark its midpoint. The deviation of this response from the objective midpoint provides an index of attentional bias, Directional Bisection Error (DBE), which is markedly rightwards in patients with left visual neglect following right hemisphere brain damage, indicating relative inattention to the left side (Schenkenberg et al., 1980). Neurotypical groups often show a subtle leftward DBE, suggesting relative over-attention to the left (‘pseudoneglect’, see Jewell & McCourt, 2000). An alternative method for characterising line bisection behaviour, known as the ‘endpoint weightings’ method, has also been developed (McIntosh et al., 2005). This method analyses the influence or ‘weighting’ that each endpoint of the line has on the participant’s response, yielding two main summary indices of performance. The first is Endpoint Weightings Bias (EWB), a measure of asymmetry that may be more sensitive than the traditional DBE to both neglect (McIntosh et al., 2005, 2017) and pseudoneglect (Mitchell et al., 2022). The second is Endpoint Weightings Sum (EWS), which has been proposed as a measure of the total (non-lateralised) attention allocated to the task. This study aims to test whether EWS is a valid measure of non-lateralised attention for the line bisection task.

The traditional line bisection task takes DBE as its dependent variable, and the two key independent variables are the length of the line and its spatial position relative to the participant. Directional biases are amplified as line length increases, so left-sided neglect patients make increasing rightward errors for longer lines (Bisiach et al., 1983; Butter et al., 1988; Nichelli et al., 1989), and healthy participants make increasing (though still small) leftward errors (see Jewell & McCourt, 2000). Patients with neglect generally show a negative (centripetal) spatial position effect, so that bisection errors become relatively more rightward when the line is presented towards the patient’s left side, and relatively more leftward when the line is presented towards the right (Heilman & Valenstein, 1979; Nichelli et al., 1989; Schenkenberg et al., 1980). By contrast, neurotypical participants show a positive (centrifugal) spatial position effect, erring further leftward for lines in left space and further rightward for lines in right space (see Jewell & McCourt, 2000). These modulations mean that the magnitude and direction of DBE will differ depending on the length and spatial location of the presented lines. 

The endpoint weightings method provides an alternative framework for administering and analysing the line bisection task, which takes advantage of response modulations across different stimulus lines (McIntosh et al., 2005). The method begins by recasting the traditional task in terms of the dependent and independent variables involved. The new dependent variable is simply the horizontal position of the response relative to the midline of the workspace (or any other fixed reference), and the new independent variables are the positions of the left and right endpoints of the line, relative to the same fixed reference point. The task is administered as a series of lines, presented one at a time, in which left and right endpoints are varied independently. The endpoint weightings analysis then quantifies the degree to which the response position (P) is modulated by changes in the left (L) and right (R) endpoint positions. The left and right ‘endpoint weightings’ are given by slope coefficients obtained by regressing P on L and R. Perfect bisection behaviour would produce symmetrical endpoint weightings of 0.5, because a shift of an endpoint causes the objective midpoint to shift by exactly half as much in the same direction. The endpoint weightings quantify the independent influences of left and right endpoints, and predict how the responses will change when the endpoint positions are varied (for instance, when line length or spatial position are manipulated). The endpoint weightings method, therefore, gives an alternative mathematical description of familiar patterns of bisection behaviour.

  1.2 Line bisection may measure generalised attention as well as spatial bias
If we assume that accurate bisection behaviour requires balanced spatial attention, then we may propose that an endpoint weighting indexes the amount of attention allocated to that end of the line (McIntosh, 2018; McIntosh et al., 2005). Given this interpretation, a participant’s performance may be summarised by two composite variables. The first is an index of lateralised attentional bias, EWB, given by the difference between the two endpoint weightings (right endpoint weighting minus left endpoint weighting), where positive values reflect a dominant influence of the right endpoint, and negative values a dominant influence of the left. Patients with left neglect have large positive values of EWB, and this index is more sensitive to neglect than the traditional index of DBE (McIntosh, 2018; McIntosh et al., 2005, 2017). Neurotypical participants have a slight negative EWB on average, and this index is similarly more sensitive to pseudoneglect than is DBE (McIntosh et al., 2005, 2019 Experiment 2). The second composite variable is the sum of the two endpoint weightings (EWS), which theoretically indexes the total amount of attention allocated to both ends of the line. Patients with neglect tend to have sub-normal values of EWS (i.e. EWS < 1) (McIntosh, 2018; McIntosh et al., 2005, 2017), and neglect is well-known to be associated with reduced overall attentional resources (see Robertson, 1993). The endpoint weightings analysis may, therefore, be capable of measuring non-lateralised attentional allocation, as well as lateralised attentional bias, for the line bisection task. The present experiment aims to test the validity of EWS as a measure of non-lateralised attention in a neurotypical sample. 

If EWS does index non-lateralised attention, then it should be modifiable by manipulations tonic (sustained) and phasic (transient) alertness, where tonic alertness refers to general wakefulness and engagement, and phasic alertness refers to a short term readiness to respond, for instance following a warning signal (Sturm & Willmes, 2001). One established way to manipulate tonic alertness is via testing time, with prolonged performance of a task reducing alertness due to fatigue and/or boredom (Benwell et al., 2013; Dufour et al., 2007; Manly et al., 2005). One way to manipulate phasic alertness is via a salient event such as an auditory tone, which may act as a warning signal, or can be an uninformative accessory stimulus causing a brief surge in physiological arousal (Hackley & Valle-Inclán, 1999a; Jepma et al., 2009; Nakano, 2002; Robertson et al., 1998). In the present experiment, we will manipulate tonic and phasic alertness to test the hypothesis that EWS is a valid measure of non-lateralised attention for the line bisection task. Our methods and expected effect sizes are informed by prior published and unpublished studies, as described below.

  1.3 
  


